### ISSUE TITLE
eventName is added to topic before checking

### ISSUE THREAD

**Issue by geekf** [sbmadhav/eventbus#1]
https://github.com/sbmadhav/eventbus/blob/master/EventBus.js#L30

This should be in the if condition provided on L31.

**Comment by sbmadhav** [comment]
I dint quite understand your comment. 
topics[ eventName ] = topics[ eventName ] || []; -> Here i am initializing to an empty array in case the a topic with that eventName does not exist already. I think this is required. We can do it in the if condition as well. But this is more convenient. Do you see a logical issue with doing it this way ?

**Comment by geekf** [comment]
What if _eventName_ is not passed or it is not string? You are doing this exact check in that _if_ condition. Also, if just _eventName_ is passed it's of no good use.

Just move L30 in the condition provided in L31.

Note: Normally I would have created a pull request but I don't feel like providing a minified version of the code :)

**Comment by sbmadhav** [comment]
Ah! Now I got what you are saying. Was short sighted when I did this. Moving the assignment inside.
